-- OBSOLETO: este script abría app_users al rol anon y ya no debe ejecutarse.
-- La creación de usuarios ahora se realiza mediante /api/admin-users.
-- Para proteger una base existente, ejecutar:
--   1. supabase_migration_existing.sql
--   2. supabase_production_security.sql
